name: unsup_amr
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.10
  - pip

  - transformers
  - datasets
  - pytorch

  # Need this for t5
  - protobuf
  - sentencepiece

  # Need this for jupyter notebooks
  - ipykernel

  # Need this for progress bar
  - ipywidgets